2025-03-05 18:02:54: [31m[Nest] 31332  - [39m03/05/2025, 6:02:54 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 18.162.133.39:30299
    at Object.createConnectionPromise [as createConnection] (D:\ProgramData\YiAiQuickDeploy\node_modules\.pnpm\mysql2@3.12.0\node_modules\mysql2\promise.js:18:31)
    at initDatabase (D:\ProgramData\YiAiQuickDeploy\dist\modules\database\initDatabase.js:1:3053)
    at bootstrap (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:3499)
    at Object.<anonymous> (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:5591)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\ProcessContainer.js:304:25
    at wrapper (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\once.js:12:16)
    at next (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\waterfall.js:96:20)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16
    at WriteStream.<anonymous> (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\Utility.js:186:13)
    at WriteStream.emit (node:events:514:28)
    at node:internal/fs/streams:75:16
    at FSReqCallback.oncomplete (node:fs:200:23)
2025-03-05 18:02:57: [31m[Nest] 31332  - [39m03/05/2025, 6:02:57 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
2025-03-05 18:02:57: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:04: [31m[Nest] 31332  - [39m03/05/2025, 6:03:04 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
2025-03-05 18:03:04: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:10: [31m[Nest] 31332  - [39m03/05/2025, 6:03:10 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (3)...[39m
2025-03-05 18:03:10: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:17: [31m[Nest] 31332  - [39m03/05/2025, 6:03:17 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (4)...[39m
2025-03-05 18:03:17: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:23: [31m[Nest] 31332  - [39m03/05/2025, 6:03:23 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (5)...[39m
2025-03-05 18:03:23: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:29: [31m[Nest] 31332  - [39m03/05/2025, 6:03:29 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (6)...[39m
2025-03-05 18:03:29: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:43: [31m[Nest] 31332  - [39m03/05/2025, 6:03:43 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (7)...[39m
2025-03-05 18:03:43: Error: connect ETIMEDOUT
    at PoolConnection._handleTimeoutError (D:\ProgramData\YiAiQuickDeploy\node_modules\.pnpm\mysql2@3.12.0\node_modules\mysql2\lib\base\connection.js:200:17)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
2025-03-05 18:03:49: [31m[Nest] 31332  - [39m03/05/2025, 6:03:49 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (8)...[39m
2025-03-05 18:03:49: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:03:55: [31m[Nest] 31332  - [39m03/05/2025, 6:03:55 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (9)...[39m
2025-03-05 18:04:12: [31m[Nest] 18632  - [39m03/05/2025, 6:04:12 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:04:14: [31m[Nest] 18632  - [39m03/05/2025, 6:04:14 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
2025-03-05 18:04:14: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 18.162.133.39:30299
    at Object.createConnectionPromise [as createConnection] (D:\ProgramData\YiAiQuickDeploy\node_modules\.pnpm\mysql2@3.12.0\node_modules\mysql2\promise.js:18:31)
    at initDatabase (D:\ProgramData\YiAiQuickDeploy\dist\modules\database\initDatabase.js:1:3053)
    at bootstrap (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:3499)
    at Object.<anonymous> (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:5591)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\ProcessContainer.js:304:25
    at wrapper (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\once.js:12:16)
    at next (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\waterfall.js:96:20)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16
    at WriteStream.<anonymous> (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\Utility.js:186:13)
    at WriteStream.emit (node:events:514:28)
    at node:internal/fs/streams:75:16
    at FSReqCallback.oncomplete (node:fs:200:23)
2025-03-05 18:04:21: [31m[Nest] 18632  - [39m03/05/2025, 6:04:21 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
2025-03-05 18:04:21: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:08: [31m[Nest] 29296  - [39m03/05/2025, 6:07:08 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 18.162.133.39:30299
    at Object.createConnectionPromise [as createConnection] (D:\ProgramData\YiAiQuickDeploy\node_modules\.pnpm\mysql2@3.12.0\node_modules\mysql2\promise.js:18:31)
    at initDatabase (D:\ProgramData\YiAiQuickDeploy\dist\modules\database\initDatabase.js:1:3053)
    at bootstrap (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:3499)
    at Object.<anonymous> (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:5591)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\ProcessContainer.js:304:25
    at wrapper (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\once.js:12:16)
    at next (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\waterfall.js:96:20)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16
    at WriteStream.<anonymous> (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\Utility.js:186:13)
    at WriteStream.emit (node:events:514:28)
    at node:internal/fs/streams:75:16
    at FSReqCallback.oncomplete (node:fs:200:23)
2025-03-05 18:07:11: [31m[Nest] 29296  - [39m03/05/2025, 6:07:11 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
2025-03-05 18:07:11: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:18: [31m[Nest] 29296  - [39m03/05/2025, 6:07:18 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
2025-03-05 18:07:18: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:25: [31m[Nest] 29296  - [39m03/05/2025, 6:07:25 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (3)...[39m
2025-03-05 18:07:25: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:31: [31m[Nest] 29296  - [39m03/05/2025, 6:07:31 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (4)...[39m
2025-03-05 18:07:31: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:38: [31m[Nest] 29296  - [39m03/05/2025, 6:07:38 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (5)...[39m
2025-03-05 18:07:38: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:44: [31m[Nest] 29296  - [39m03/05/2025, 6:07:44 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (6)...[39m
2025-03-05 18:07:44: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:50: [31m[Nest] 29296  - [39m03/05/2025, 6:07:50 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (7)...[39m
2025-03-05 18:07:50: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:07:57: [31m[Nest] 29296  - [39m03/05/2025, 6:07:57 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (8)...[39m
2025-03-05 18:07:57: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:08:03: [31m[Nest] 29296  - [39m03/05/2025, 6:08:03 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (9)...[39m
2025-03-05 18:08:31: [31m[Nest] 20168  - [39m03/05/2025, 6:08:31 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: connect ECONNREFUSED 18.162.133.39:30299
    at Object.createConnectionPromise [as createConnection] (D:\ProgramData\YiAiQuickDeploy\node_modules\.pnpm\mysql2@3.12.0\node_modules\mysql2\promise.js:18:31)
    at initDatabase (D:\ProgramData\YiAiQuickDeploy\dist\modules\database\initDatabase.js:1:3053)
    at bootstrap (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:3499)
    at Object.<anonymous> (D:\ProgramData\YiAiQuickDeploy\dist\main.js:1:5591)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\ProcessContainer.js:304:25
    at wrapper (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\once.js:12:16)
    at next (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\waterfall.js:96:20)
    at D:\ProgramData\nvm\v18.17.1\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16
    at WriteStream.<anonymous> (D:\ProgramData\nvm\v18.17.1\node_modules\pm2\lib\Utility.js:186:13)
    at WriteStream.emit (node:events:514:28)
    at node:internal/fs/streams:75:16
    at FSReqCallback.oncomplete (node:fs:200:23)
2025-03-05 18:08:34: [31m[Nest] 20168  - [39m03/05/2025, 6:08:34 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
2025-03-05 18:08:34: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:08:41: [31m[Nest] 20168  - [39m03/05/2025, 6:08:41 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
2025-03-05 18:08:41: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:08:47: [31m[Nest] 20168  - [39m03/05/2025, 6:08:47 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (3)...[39m
2025-03-05 18:08:47: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:08:54: [31m[Nest] 20168  - [39m03/05/2025, 6:08:54 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (4)...[39m
2025-03-05 18:08:54: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:09:00: [31m[Nest] 20168  - [39m03/05/2025, 6:09:00 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (5)...[39m
2025-03-05 18:09:00: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:09:07: [31m[Nest] 20168  - [39m03/05/2025, 6:09:07 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (6)...[39m
2025-03-05 18:09:07: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:09:13: [31m[Nest] 20168  - [39m03/05/2025, 6:09:13 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (7)...[39m
2025-03-05 18:09:13: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:09:20: [31m[Nest] 20168  - [39m03/05/2025, 6:09:20 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (8)...[39m
2025-03-05 18:09:20: Error: connect ECONNREFUSED 18.162.133.39:30299
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
2025-03-05 18:09:26: [31m[Nest] 20168  - [39m03/05/2025, 6:09:26 PM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (9)...[39m
2025-03-05 18:09:40: [31m[Nest] 34384  - [39m03/05/2025, 6:09:40 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:10:04: [31m[Nest] 34384  - [39m03/05/2025, 6:10:04 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:10:06: [31m[Nest] 34384  - [39m03/05/2025, 6:10:06 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:10:21: [31m[Nest] 34384  - [39m03/05/2025, 6:10:21 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:13:21: [31m[Nest] 16144  - [39m03/05/2025, 6:13:21 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:13:28: [31m[Nest] 16144  - [39m03/05/2025, 6:13:28 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:13:28: [31m[Nest] 16144  - [39m03/05/2025, 6:13:28 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:13:47: [31m[Nest] 35968  - [39m03/05/2025, 6:13:47 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:13:54: [31m[Nest] 35968  - [39m03/05/2025, 6:13:54 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:13:54: [31m[Nest] 35968  - [39m03/05/2025, 6:13:54 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:14:17: [31m[Nest] 20608  - [39m03/05/2025, 6:14:17 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:14:24: [31m[Nest] 20608  - [39m03/05/2025, 6:14:24 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:14:24: [31m[Nest] 20608  - [39m03/05/2025, 6:14:24 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:14:37: [31m[Nest] 36656  - [39m03/05/2025, 6:14:37 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Missing credentials for "PLAIN"[39m
2025-03-05 18:14:44: [31m[Nest] 36656  - [39m03/05/2025, 6:14:44 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:14:44: [31m[Nest] 36656  - [39m03/05/2025, 6:14:44 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:33:24: [31m[Nest] 33412  - [39m03/05/2025, 6:33:24 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Invalid login: 535 Error: authentication failed[39m
2025-03-05 18:33:32: [31m[Nest] 33412  - [39m03/05/2025, 6:33:32 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:33:33: [31m[Nest] 33412  - [39m03/05/2025, 6:33:33 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:37:04: [31m[Nest] 30904  - [39m03/05/2025, 6:37:04 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Invalid login: 535 Error: authentication failed[39m
2025-03-05 18:37:13: [31m[Nest] 30904  - [39m03/05/2025, 6:37:13 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 18:37:14: [31m[Nest] 30904  - [39m03/05/2025, 6:37:14 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 18:38:04: [31m[Nest] 30904  - [39m03/05/2025, 6:38:04 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-05 19:00:00: [31m[Nest] 30904  - [39m03/05/2025, 7:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 19:50:29: [31m[Nest] 30904  - [39m03/05/2025, 7:50:29 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-05 19:55:19: [31m[Nest] 30904  - [39m03/05/2025, 7:55:19 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-05 20:00:00: [31m[Nest] 30904  - [39m03/05/2025, 8:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 20:00:27: [31m[Nest] 30904  - [39m03/05/2025, 8:00:27 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-05 20:05:00: [31m[Nest] 30904  - [39m03/05/2025, 8:05:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:10:00: [31m[Nest] 30904  - [39m03/05/2025, 8:10:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:15:00: [31m[Nest] 30904  - [39m03/05/2025, 8:15:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:20:00: [31m[Nest] 30904  - [39m03/05/2025, 8:20:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:25:00: [31m[Nest] 30904  - [39m03/05/2025, 8:25:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:30:00: [31m[Nest] 30904  - [39m03/05/2025, 8:30:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:35:00: [31m[Nest] 30904  - [39m03/05/2025, 8:35:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:40:00: [31m[Nest] 30904  - [39m03/05/2025, 8:40:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:45:00: [31m[Nest] 30904  - [39m03/05/2025, 8:45:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:50:00: [31m[Nest] 30904  - [39m03/05/2025, 8:50:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 20:55:00: [31m[Nest] 30904  - [39m03/05/2025, 8:55:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 21:00:00: [31m[Nest] 30904  - [39m03/05/2025, 9:00:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 21:00:00: [31m[Nest] 30904  - [39m03/05/2025, 9:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 21:05:00: [31m[Nest] 30904  - [39m03/05/2025, 9:05:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 21:10:00: [31m[Nest] 30904  - [39m03/05/2025, 9:10:00 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-05 21:15:10: [31m[Nest] 30904  - [39m03/05/2025, 9:15:10 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: connect ETIMEDOUT[39m
2025-03-05 22:00:00: [31m[Nest] 30904  - [39m03/05/2025, 10:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 23:00:00: [31m[Nest] 30904  - [39m03/05/2025, 11:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-05 23:50:21: [31m[Nest] 30904  - [39m03/05/2025, 11:50:21 PM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-06 00:00:00: [31m[Nest] 30904  - [39m03/06/2025, 12:00:00 AM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-06 00:05:35: [31m[Nest] 30904  - [39m03/06/2025, 12:05:35 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-06 00:10:00: [31m[Nest] 30904  - [39m03/06/2025, 12:10:00 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-06 00:15:00: [31m[Nest] 30904  - [39m03/06/2025, 12:15:00 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-06 00:20:00: [31m[Nest] 30904  - [39m03/06/2025, 12:20:00 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-06 00:25:00: [31m[Nest] 30904  - [39m03/06/2025, 12:25:00 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-06 00:35:40: [31m[Nest] 30904  - [39m03/06/2025, 12:35:40 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mQueryFailedError: read ECONNRESET[39m
2025-03-06 00:40:00: [31m[Nest] 30904  - [39m03/06/2025, 12:40:00 AM [31m  ERROR[39m [38;5;3m[Scheduler] [39m[31mError: getaddrinfo ENOTFOUND hkg1.clusters.zeabur.com[39m
2025-03-06 00:41:41: [31m[Nest] 35168  - [39m03/06/2025, 12:41:41 AM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mTransporter is ready[39m
2025-03-06 00:41:50: [31m[Nest] 35168  - [39m03/06/2025, 12:41:50 AM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-06 00:41:50: [31m[Nest] 35168  - [39m03/06/2025, 12:41:50 AM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-24 21:57:52: [31m[Nest] 9988  - [39m03/24/2025, 9:57:52 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mTransporter is ready[39m
2025-03-24 21:57:56: [31m[Nest] 9988  - [39m03/24/2025, 9:57:56 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-24 21:57:58: [31m[Nest] 9988  - [39m03/24/2025, 9:57:58 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-24 21:58:49: [31m[Nest] 9988  - [39m03/24/2025, 9:58:49 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-24 22:00:00: [31m[Nest] 9988  - [39m03/24/2025, 10:00:00 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-24 22:07:23: [31m[Nest] 9988  - [39m03/24/2025, 10:07:23 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-24 22:47:17: [31m[Nest] 14948  - [39m03/24/2025, 10:47:17 PM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mTransporter is ready[39m
2025-03-24 22:47:23: [31m[Nest] 14948  - [39m03/24/2025, 10:47:23 PM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-24 22:47:24: [31m[Nest] 14948  - [39m03/24/2025, 10:47:24 PM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-25 02:13:55: [31m[Nest] 12336  - [39m03/25/2025, 2:13:55 AM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mTransporter is ready[39m
2025-03-25 02:13:59: [31m[Nest] 12336  - [39m03/25/2025, 2:13:59 AM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
2025-03-25 02:14:01: [31m[Nest] 12336  - [39m03/25/2025, 2:14:01 AM [31m  ERROR[39m [38;5;3m[OfficialService] [39m[31m还未配置微信的appId和secret、配置后才可进行微信扫码登录！！！[39m
2025-03-25 02:16:04: [31m[Nest] 12336  - [39m03/25/2025, 2:16:04 AM [31m  ERROR[39m [38;5;3m[GlobalConfigService] [39m[31m百度敏感词初始化失败，如果需要敏感检测、请前往后台系统配置![39m
